# Generated by Django 5.2.9 on 2025-12-18 10:09

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorProfile',
            fields=[
                ('visitor_id', models.CharField(help_text='Anonymous visitor identifier (UUID stored as string).', max_length=64, primary_key=True, serialize=False)),
                ('first_seen', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this visitor was first seen.')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Timestamp when this visitor was last seen.')),
                ('last_ip', models.GenericIPAddressField(blank=True, help_text='Last IP address observed for this visitor (for geolocation).', null=True)),
                ('country', models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 country code (e.g. 'PK', 'US').", max_length=2, null=True)),
                ('city', models.CharField(blank=True, help_text='City or region name derived from geolocation.', max_length=128, null=True)),
                ('latitude', models.FloatField(blank=True, help_text='Approximate latitude (rounded, optional).', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Approximate longitude (rounded, optional).', null=True)),
            ],
            options={
                'verbose_name': 'Visitor Profile',
                'verbose_name_plural': 'Visitor Profiles',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the product was viewed.')),
                ('country', models.CharField(blank=True, help_text='Country code at time of view (copied from visitor, if available).', max_length=2, null=True)),
                ('city', models.CharField(blank=True, help_text='City/region at time of view (copied from visitor, if available).', max_length=128, null=True)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude at time of view (optional, rounded).', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude at time of view (optional, rounded).', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Optional truncated user agent string for device-level insights.', max_length=256, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='catalog.product')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='catalog.visitorprofile')),
            ],
            options={
                'verbose_name': 'Product View',
                'verbose_name_plural': 'Product Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['visitor', 'viewed_at'], name='catalog_pro_visitor_8f17c0_idx'), models.Index(fields=['product', 'viewed_at'], name='catalog_pro_product_e125b2_idx'), models.Index(fields=['country', 'viewed_at'], name='catalog_pro_country_51182b_idx')],
            },
        ),
    ]
