# Generated by Django 5.2.9 on 2025-12-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_visitorprofile_alter_product_price_productview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productview',
            name='country',
            field=models.CharField(blank=True, help_text='Country name at time of view (copied from visitor, if available).', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='visitorprofile',
            name='country',
            field=models.CharField(blank=True, help_text="Country name (e.g. 'Pakistan', 'United States').", max_length=128, null=True),
        ),
    ]
