# Generated by Django 5.2.9 on 2025-12-19 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productview_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the product was liked.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='catalog.product')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_likes', to='catalog.visitorprofile')),
            ],
            options={
                'verbose_name': 'Product Like',
                'verbose_name_plural': 'Product Likes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['visitor', 'created_at'], name='catalog_pro_visitor_da3635_idx'), models.Index(fields=['product', 'created_at'], name='catalog_pro_product_273d08_idx')],
                'unique_together': {('visitor', 'product')},
            },
        ),
    ]
