# Generated by Django 5.2.9 on 2025-12-20 05:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Optional reviewer name (can be anonymous).', max_length=200, null=True)),
                ('review_text', models.TextField(help_text='Review content (required).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the review was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the review was last updated.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='catalog.visitorprofile')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='catalog_pro_product_adc547_idx'), models.Index(fields=['visitor', 'created_at'], name='catalog_pro_visitor_b0f999_idx')],
            },
        ),
    ]
