# Generated by Django 5.2.9 on 2025-12-21 08:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="User's first name.", max_length=100)),
                ('last_name', models.CharField(help_text="User's last name.", max_length=100)),
                ('username', models.CharField(db_index=True, help_text='Unique username for login.', max_length=150, unique=True)),
                ('email', models.EmailField(db_index=True, help_text="User's email address (must be unique).", max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(help_text='Hashed password (never store plain text).', max_length=128)),
                ('visitor', models.ForeignKey(blank=True, help_text='Linked visitor profile for cross-device tracking synchronization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='catalog.visitorprofile')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.CharField(help_text='The security question text.', max_length=255)),
                ('answer_hash', models.CharField(help_text='Hashed answer to the security question (never store plain text).', max_length=255)),
                ('question_order', models.IntegerField(choices=[(1, 'Question 1'), (2, 'Question 2'), (3, 'Question 3')], help_text='Order of this question (1, 2, or 3). Each user must have exactly 3 questions.')),
                ('user', models.ForeignKey(help_text='User who owns this security question.', on_delete=django.db.models.deletion.CASCADE, related_name='security_questions', to='catalog.user')),
            ],
            options={
                'verbose_name': 'Security Question',
                'verbose_name_plural': 'Security Questions',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='catalog_use_usernam_eb0e74_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='catalog_use_email_481755_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['visitor'], name='catalog_use_visitor_42f6cc_idx'),
        ),
        migrations.AddIndex(
            model_name='securityquestion',
            index=models.Index(fields=['user', 'question_order'], name='catalog_sec_user_id_d1da92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='securityquestion',
            unique_together={('user', 'question_order')},
        ),
    ]
