# Generated by Django 5.2.9 on 2025-12-23 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Email address this OTP was sent to.', max_length=254)),
                ('code', models.CharField(help_text='4-digit verification code.', max_length=4)),
                ('purpose', models.CharField(choices=[('signup', 'Signup'), ('password_reset', 'Password Reset')], help_text='Purpose of this OTP (signup or password reset).', max_length=32)),
                ('expires_at', models.DateTimeField(help_text='When this code expires and becomes invalid.')),
                ('attempt_count', models.IntegerField(default=0, help_text='Number of invalid attempts made with this code.')),
                ('max_attempts', models.IntegerField(default=3, help_text='Maximum allowed invalid attempts before code is locked.')),
                ('used', models.BooleanField(default=False, help_text='Whether this code has already been successfully used.')),
            ],
            options={
                'verbose_name': 'Email OTP',
                'verbose_name_plural': 'Email OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', 'expires_at'], name='catalog_ema_email_03411b_idx')],
            },
        ),
    ]
