# Generated by Django 5.2.9 on 2025-12-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_add_email_otp_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.CharField(choices=[('s_corp', 'S-Corp'), ('c_corp', 'C-Corp'), ('llc', 'LLC'), ('self_employed', 'Self Employed'), ('other', 'Other')], default='other', help_text='Type of business entity.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='ein_number',
            field=models.CharField(blank=True, help_text='Employer Identification Number (EIN) in format XX-XXXXXXX.', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='llc_certificate',
            field=models.FileField(blank=True, help_text='LLC certificate document (optional).', null=True, upload_to='user_documents/llc_certificates/'),
        ),
    ]
