# Generated by Django 5.2.9 on 2025-12-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_add_business_fields_to_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecurityQuestion',
        ),
    ]
