# Generated by Django 5.2.9 on 2025-12-25 08:05

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_security_question_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='llc_certificate_name',
            field=models.CharField(blank=True, help_text='Original filename of the LLC certificate document.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='llc_certificate',
            field=models.FileField(blank=True, help_text='LLC certificate document (optional).', null=True, upload_to=catalog.models.llc_certificate_upload_to),
        ),
    ]
